# Generated by Django 4.2.5 on 2023-09-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_city_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='')),
                ('company', models.CharField(max_length=256, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.language', verbose_name='')),
            ],
            options={
                'verbose_name': 'Vacancy ',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
